export const GENERATE_GAME = 'GENERATE_GAME';
export const START_GAME = 'START_GAME';
export const CHANGE_TABLE_SIZE = 'CHANGE_TABLE_SIZE';
export const GAME_STEP = 'GAME_STEP';
export const CALCULATE_SCORE = 'CALCULATE_SCORE';
export const IS_GAME_FINISHED = 'IS_GAME_FINISHED';